id: chgk_pack.field_informacia
uuid: c237671f-dfd9-45b2-b523-35a360fd1b23
status: true
langcode: ru
name: info
entity_type: chgk_pack
type: text_long
settings: {  }
module: text
locked: false
cardinality: 1
translatable: false
indexes: {  }
