id: chgk_pack.date_start
uuid: 01987f29-ee54-40fc-9a00-e03d297a06ac
status: true
langcode: ru
name: date_start
entity_type: chgk_pack
type: datetime
settings:
  datetime_type: date
module: datetime
locked: false
cardinality: 1
translatable: false
indexes: {  }
