label: Бескрылка
description: Бескрылка &ndash; стихотворная загадка на угадывание цитаты по контексту. Из стихотворного текста удаляется часть текста, которую надо отгадать. Эта часть должна являться крылатой фразой или словосочетанием, известной строкой из стихотворения или песни.
